### ISSUE TITLE
Deprecation error found when building WWDC21 RecoverApp

### ISSUE THREAD

**Issue by wbj** [carekit-apple/WWDC21-RecoverApp#1]
ORKKeychainWrapper.m, line 53 
"WWDC21-RecoverApp/ResearchKit/ResearchKit/Common/ORKKeychainWrapper.m:53:37: 'archivedDataWithRootObject:' is deprecated: first deprecated in iOS 12.0 - Use +archivedDataWithRootObject:requiringSecureCoding:error: instead"

macOS Big Sur (11.3.1), Xcode Version 12.5 (12E262)

**Comment by erik-apple** [comment]
Thanks for reporting this. The underlying issue is in the ResearchKit framework. We'll issue a fix in ResearchKit and then update the commit checked out in this repo.

**Comment by erik-apple** [comment]
There is a [PR](https://github.com/ResearchKit/ResearchKit/pull/1461) open against ResearchKit that will resolve this warning.

**Comment by erik-apple** [comment]
This has been fixed!

You will need to make sure that you pick up the checkout of RK in your project. Depending on your comfort with git, a fresh clone of the project may be the easiest way to get caught up!
