### ISSUE TITLE
Many build errors

### ISSUE THREAD

**Issue by nashysolutions** [carekit-apple/WWDC21-RecoverApp#3]
# Environmnent

Xcode 13 beta 2 (13A5155e)

# Snapshots

<img width="278" alt="Screenshot 2021-07-04 at 10 32 32" src="https://user-images.githubusercontent.com/64097812/124380197-54821500-dcb3-11eb-831a-288b00b9e9b4.png">

<img width="644" alt="Screenshot 2021-07-04 at 10 34 20" src="https://user-images.githubusercontent.com/64097812/124380210-695ea880-dcb3-11eb-98d1-8e5594343a28.png">

<img width="274" alt="Screenshot 2021-07-04 at 10 32 35" src="https://user-images.githubusercontent.com/64097812/124380218-77142e00-dcb3-11eb-8cdc-fcdf8cddc409.png">

# Steps to reproduce 

1. git clone via source tree App
2. build and run

**Comment by nashysolutions** [comment]
There was a moment during the pull that a dialogue message popped up, via source app, mentioning LFS installation. I selected 'yes, go ahead' and the pull continued. Investigating further.

**Comment by nashysolutions** [comment]
Using the exact instructions in your readme, I can see that the options '--recurse-submodule' is present.

```
git clone --recurse-submodule https://github.com/carekit-apple/WWDC21-RecoverApp.git
```

However, using this approach does not pull all of the files.

<img width="208" alt="Screenshot 2021-07-04 at 10 40 27" src="https://user-images.githubusercontent.com/64097812/124380379-41bc1000-dcb4-11eb-91e9-03088038dd7a.png">

But as you can see there is some mention of 'LFS' again. 

Investigating further...

**Comment by nashysolutions** [comment]
Stacks has raised [the question](https://stackoverflow.com/questions/56283415/how-do-i-clone-a-repository-that-includes-git-lfs-files/56284009) regarding LFS files, but the suggested command does not seem to work.

$ git lfs install     
$ git: 'lfs' is not a git command. See 'git --help'.

😟

$ git --version
$ git version 2.30.1 (Apple Git-130)

**Comment by zhang-bo-lilly** [comment]
@nashysolutions, if this happens on an M1 Mac, try running both Terminal and Xcode using Rosetta which solved my issue.

**Comment by Hengyu** [comment]
You could do this to solve the errors:
`cd ResearchKit`
`git checkout 90c68d0d195f23fff1f618a9a4ffa518be9ac845`

Update the submodule `ResearchKit` to https://github.com/ResearchKit/ResearchKit/commit/90c68d0d195f23fff1f618a9a4ffa518be9ac845 can solve the problem

**Comment by nashysolutions** [comment]
Following your advice @Hengyu I now have a different set of errors and warnings.

<img width="586" alt="Screenshot 2022-04-07 at 09 52 02" src="https://user-images.githubusercontent.com/64097812/162160653-f5d793b0-c797-4528-b8b9-886014860bad.png">
<img width="266" alt="Screenshot 2022-04-07 at 09 51 32" src="https://user-images.githubusercontent.com/64097812/162160659-5f75400f-1a59-4416-8bff-0c71d333276d.png">

XCode 13.3

**Comment by Hengyu** [comment]
hey @nashysolutions , I'm using Xcode 13.3, and have no problem on it. Can you make a clean fetching of this repo and then try to checkout the previous commit for its submodule `ResearchKit`?

**Comment by nashysolutions** [comment]
Tried fresh pull. No luck.

**Comment by Hengyu** [comment]
Okay, let me make a sample project, then upload to GitHub for you!

**Comment by Hengyu** [comment]
@nashysolutions here: https://github.com/Hengyu/WWDC21-RecoverApp/tree/hengyu_update_submodule
<img width="1252" alt="1" src="https://user-images.githubusercontent.com/4032674/162601160-7da3765b-2f48-431a-ad38-8cfc756ebd05.png">

**Comment by nashysolutions** [comment]
Thank you @Hengyu
